version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  aws-ecr: circleci/aws-ecr@7.2.0

commands:
  test:
    steps:
      - run: |
          docker run --rm \
            $AWS_ECR_ACCOUNT_URL/$APP_NAME:$CIRCLE_BUILD_NUM \
            /root/.local/bin/pytest -v

executors:
  circlecipython:
    docker:
      - image: circleci/python

jobs:
  test:
    executor: circlecipython
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7 # docker version
      - test

workflows:
  build-docker:
    jobs:
      - aws-ecr/build-and-push-image:
          name: build-and-push-image
          context: AWS
          checkout: true
          tag: $(cat VERSION)
          repo: demo
          filters:
            branches:
              only:
                - master
      - test:
          context: AWS
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
