version: 2.1

commands:
  build:
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7 # docker version
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t test:$TAG .
          echo $DOCKER_PASS

executors:
  dind:
    docker:
      - image: circleci/golang:1.15

jobs:
  build:
    executor: dind
    steps:
      - build

workflows:
  version: 2
  build-docker:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
