version: 2.1

commands:
  build:
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7 # docker version
      - run: docker build -t test .

executors:
  dind:
    docker:
      - image: novemberde/node-awscli:docker

jobs:
  build:
    executor: dind
    working_directory: ~/devops_sample_app_python
    steps:
      - build

workflows:
  version: 2
  build-docker:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
