version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

commands:
  build:
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7 # docker version
      - run: |
          docker build \
            -t $AWS_ECR_URL/$APP_NAME:$CIRCLE_BUILD_NUM \
            -t $AWS_ECR_URL/$APP_NAME:latest .
  test:
    steps:
      - run: |
          docker run --rm \
            $AWS_ECR_URL/$APP_NAME:$CIRCLE_BUILD_NUM \
            /root/.local/bin/pytest -v
  push:
    steps:
      - run: |
          docker push $AWS_ECR_URL/$APP_NAME:$CIRCLE_BUILD_NUM

executors:
  circlecipython:
    docker:
      - image: circleci/python

jobs:
  build:
    executor: circlecipython
    steps:
      - build

workflows:
  build-docker:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
