version: 2.1
jobs:
  build:
    docker:
      - image: novemberde/node-awscli:docker
    working_directory: ~/devops_sample_app_python
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t test .

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
