version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0

commands:
  build:
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7 # docker version
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t test:$TAG .

executors:
  dind:
    docker:
      - image: circleci/python

jobs:
  build:
    executor: dind
    steps:
      - build

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: demo
          dockerfile: Dockerfile
          context: .
          skip-when-tags-exist: false
          tag: '1.0.3'
#  build-docker:
#    jobs:
#      - build:
#          filters:
#            branches:
#              ignore:
#                - develop
#                - /feature-.*/
