version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  AfterInstall:
    - location: kill_process.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: run_process.sh
      timeout: 10
      runas: ec2-user