version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  ApplicationStop:
    - location: kill_process.sh
      timeout: 100
      runas: ec2-user
  ApplicationStart:
    - location: run_process.sh
      timeout: 3600
      runas: ec2-user