name: Build Docker Image

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - '.dockerignore'
      - 'README.md'
#    paths:
#      - '**.py'
  pull_request:
    branches: [ master ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Build the Docker image
      run: |
        docker build -f Dockerfile -t 657976307134.dkr.ecr.ap-northeast-2.amazonaws.com:1.0.0 .

    - name: ECR login
      uses: thalesvon/ecr-login@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2
        AWS_DEFAULT_OUTPUT: json
      with:
        args: 'get-login --no-include-email --region ${AWS_REGION}'
