name: CI/CD

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - '.dockerignore'
      - 'README.md'
#    paths:
#      - '**.py'
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v2
        with:
          repository: dev-chulbuji/devops_k8s
          path: deploy-k8s

      - name: Replace image in helm values
        run: |
          cat deploy-k8s/demo/values.yaml