name: CI/CD

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - '.dockerignore'
      - 'README.md'
#    paths:
#      - '**.py'
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set var
        id: set-var
        run: |
          echo ::set-output name=IMAGE_TAG::$(cat VERSION)

      - name: Checkout Target Repository
        uses: actions/checkout@v2
        with:
          repository: dev-chulbuji/devops_k8s
          path: deploy-k8s

      - name: Replace image tag in helm values
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -i '.image.tag = ${{ steps.set-var.outputs.IMAGE_TAG }}' 'deploy-k8s/demo/values.yaml'