name: CI/CD

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - '.dockerignore'
      - 'README.md'
#    paths:
#      - '**.py'
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v2
        with:
          repository: dev-chulbuji/devops_k8s
          path: deploy-k8s

      - name: Replace image tag in helm values
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -i '.image.tag = "1.0.3"' 'deploy-k8s/demo/values.yaml'

      - name: Commit helm repo
        env:
          token: ${{ secrets.GH_TOKEN }}
        run: |
          cd deploy-k8s
          git config --global user.email "dev-chulbuji@gmail.com"
          git config --global user.name "dev-chulbuji"

          git add .;
          git commit --message "wip";

          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | \
              xargs -L1 git config --unset-all

          git push origin master